services:
  dynamic-pricing-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamic-pricing-tool-ru
    restart: always
    ports:
      - "5004:5004"
    volumes:
      - ./logs:/dynamic-pricing-tool-ru/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
